### ISSUE TITLE
LAS 3.0 : tests/test_read_3.0.py:test_read_v30_sample panics reading ~Test-Data

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#384] opened 2020-09-05 23:51 UTC
#### How to see the error:
This error can be duplicated by commenting out `@pytest.mark.skip` on test_read_v30_sample() and running `pytest tests/test_read_30.py`

#### Error message:
```python
try:
                    values = read_line(line, section_name=parser.section_name2)
                except:
                    message = 'Line {} (section {}): "{}"'.format(line_no + 1, title, line)
                    if ignore_header_errors:
                        logger.warning(message)
                    else:
>                       raise exceptions.LASHeaderError(message)
E                       lasio.exceptions.LASHeaderError: Line 196 (section ~Test_Data | Test_Definition): "1,1500,1505,TSTM,13243,Weak Blow"

lasio/reader.py:695: LASHeaderError
```

**Comment by dcslagel** [comment] 2020-09-08 22:57
A proposed fix for this is in pull-request https://github.com/kinverarity1/lasio/pull/385

**Comment by kinverarity1** [comment] 2020-09-12 05:34
Closing because #385 has been merged and this test is now passing as intended.

**Closed by kinverarity1** 2020-09-12 05:34 UTC
