### ISSUE TITLE
Step 0.1 m

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [kinverarity1/lasio#415] opened 2021-01-03 10:19 UTC
I use step 0.1 meter in the program, but in las file :  step.m 0.10000000000002274: STEP
I change it in las_wr. well. STEP.value = '0.1' or las_wr. well=0.1 but nothing changes.

When adding a curve, how to change the number of characters after each curve individually, if they are added from a one-dimensional array.

las_wr.append_curve('DEPT', dept, 'm', 'dept of well', 'float')
#0.1 м

las_wr.append_curve('ph07', ph07_k, 'grad', 'ph of zond_07', 'float')
las_wr.append_curve('ph10', ph10_k, 'grad', 'ph of zond_10', 'float')

#0.001

las_wr.write(Las_wr_patch, version=2.0)

not work

column_fmt_f={0: '%.1f',
              1: '%.3f', 
              2: '%.3f', 
              3: '%.3f',
              4: '%.3f', 
              5: '%.3f',
              6: '%.3f'}

lasio.writer.write(las_wr, 
                   Las_wr_patch, 
                   version='2.0',
                   wrap=None, 
                   STRT=dept[0], 
                   STOP=dept[-1], 
                   STEP=0.1, 
                   fmt='%.1f', 
                   column_fmt={0: '%.3f'}, 
                   len_numeric_field=40, 
                   data_width=79, 
                   header_width=60)

or 

lasio.writer.write(las_wr, 
                   Las_wr_patch, 
                   version='2.0',
                   wrap=None, 
                   STRT=dept[0], 
                   STOP=dept[-1], 
                   STEP=0.1, 
                   fmt='%.1f', 
                   column_fmt=column_fmt_f, 
                   len_numeric_field=40, 
                   data_width=79, 
                   header_width=60)

**Comment by kinverarity1** [comment] 2021-03-17 00:43
Thank you for raising this issue - it is a duplicate of #404 and also the related #405, so please keep an eye on those issues; I will close this to consolidate discussion there.

**Closed by kinverarity1** 2021-03-17 00:43 UTC
