### ISSUE TITLE
Degree symbol is making reader break

### ISSUE THREAD

**Issue by EvanBianco** [kinverarity1/lasio#166] opened 2017-10-24 13:26 UTC
In the `~Parameter Information` section of the attached here, the `reader.py` is throwing an error presumably when it encounters the degree symbol in the latitude and longitude fields. 

```
LATI .        0° 0' 0  N                 :Latitude
LONG .        0° 0' 0  E                 :Longitude
```

The error message I'm getting has something to do with codecs. Is this something we can fix with the reader or it a problem that has to do with my Python installation?

[1045387215_top100ft.txt]
(https://github.com/kinverarity1/lasio/files/1410966/1045387215_top100ft.txt)

**Comment by kwinkunks** [comment] 2017-10-24 13:38
Here's the traceback...

```
>>> l = lasio.read('/Users/matt/Downloads/1045387215_top100ft.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/anaconda/envs/welly/lib/python3.5/site-packages/lasio/las.py", line 1269, in read
    return LASFile(file_ref, **kwargs)
  File "/Users/matt/anaconda/envs/welly/lib/python3.5/site-packages/lasio/las.py", line 378, in __init__
    self.read(file_ref, **kwargs)
  File "/Users/matt/anaconda/envs/welly/lib/python3.5/site-packages/lasio/las.py", line 403, in read
    f = open_file(file_ref, **kwargs)
  File "/Users/matt/anaconda/envs/welly/lib/python3.5/site-packages/lasio/las.py", line 1059, in open_file
    autodetect_encoding_chars)
  File "/Users/matt/anaconda/envs/welly/lib/python3.5/site-packages/lasio/las.py", line 1105, in get_unicode_from_filename
    data = f.read()
  File "/Users/matt/anaconda/envs/welly/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 3243: invalid start byte
>>
```

**Comment by kwinkunks** [comment] 2017-10-24 13:49
OK, this works... 

    l = lasio.read('/Users/matt/Downloads/1045387215_top100ft.txt', encoding='utf-8')

I guess the default is... ASCII? (Imagine that!)

**Comment by kwinkunks** [comment] 2017-10-24 13:59
I guess the problem is there are no BOM chars. I wonder if a good approach would be to put a try-except around it and attempt to read with a couple of common codecs.

So much for the log ASCII standard :) I'm sure someone thought they were very clever knowing how to type a degree symbol.

**Comment by dagrha** [comment] 2017-10-24 15:57
For what it's worth, when I run
```
import chardet
with open('~/Downloads/1045387215_top100ft.txt', 'rb') as f:
    print(chardet.detect(f.read()))
```

I get this as a result:
```
{'encoding': 'ISO-8859-1', 'language': '', 'confidence': 0.73}
```

So encoding appears to be `ISO-8859-1` rather than `utf-8`. 

I had thought that lasio tries to decode with `utf-8` by default (hence the `UnicodeDecodeError` when something incompatible gets passed, like `windows-1252` for example-- in other words, it's trying to decode by assuming `utf-8` but finds incompatible bytes), so it's surprising to me that doing `encoding='utf-8'` works while specifying nothing does not work.

`autodetect_encoding` can be pretty slow since it uses chardet IIRC. Try/except could make sense in lasio itself, or one could do the try/except when attempting to read an las. This way chardet is not being run on every las-- only on the ones that need it:
```
try:
    l = lasio.read(file)
except UnicodeDecodeError:
    l = lasio.read(file, autodetect_encoding=True)
```

**Comment by VelizarVESSELINOV** [comment] 2017-10-24 16:08
Why you don’t use a fast version of chardet?
“cChardet is high speed universal character encoding detector“
https://pypi.python.org/pypi/cchardet/2.1.0

**Comment by dagrha** [comment] 2017-10-24 17:59
Thanks Velizar. Looks like Lasio uses cChardet if it is installed-- awesome. That is probably better to use for speed considerations. :+1:

**Comment by kinverarity1** [comment] 2017-10-25 12:59
I can't reproduce the error! Is it because I'm running windows and thus the default python encoding is correct?

The philosophy I've been guided by is to make it "just work" out of the box, so perhaps the default behaviour should be:

1. By default use codecs.open(encoding=None) (default system python encoding, which is itself a bit of a mystery to me)
2. If UnicodeDecodeError, catch and 
2b. If cchardet (fallback chardet) installed, reload with autodetect_encoding=True
2c. If [c]chardet not installed, print warning to user recommending installation, but then try reloading with common encodings until we avoid the exception.
2c. If no success, re-raise the original UnicodeDecodeError

Does this sound like a happy medium?

**Comment by kinverarity1** [comment] 2017-10-25 13:07
@dagrha that's interesting!

 I think the speed difference between cchardet and ordinary open is less pronounced with how lasio's autodetect_encoding works. Lasio sends only the first 40e3 characters to ``[c]chardet.detect()`` and then opens the whole for using ``codecs.open(encoding="blah-blah")`` for now the relatively slow code elsewhere in the reader dominates things. 

Once I get around to optimising it that might change.

**Comment by dagrha** [comment] 2017-10-26 02:27
What you propose for handling the UnicodeDecodeError makes a lot of sense to me.

Looking at reader.py, I see what you mean now-- very clever to only send the first 32 bytes to chardet!

**Comment by kinverarity1** [comment] 2017-10-27 04:13
I need to get my hands on a linux installation to try and reproduce the error and then will work on the fix - maybe next week.

**Comment by kinverarity1** [comment] 2017-10-29 08:37
@EvanBianco I was never able to reproduce the error with your file on Windows machine, but it is hopefully fixed in master now. Could you let me know if it is still not working with just  a straight call to ``lasio.read()``?

**Comment by kinverarity1** [comment] 2017-12-19 10:40
Closing until confirmation

**Closed** 2018-01-01 10:04 UTC
Labels: bug
