### ISSUE TITLE
las_version.py uses pkg_resources which is now discouraged

### ISSUE THREAD

**Issue by sfc-gh-twhite** [kinverarity1/lasio#537] opened 2022-11-30 22:03 UTC
**Is your feature request related to a problem? Please describe.**
When attempting to use lasio in various environments, I'm encountering a Python environment issue due to using [pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html). 

**Describe the solution you'd like**
The [las_version.py](https://github.com/kinverarity1/lasio/blob/main/lasio/las_version.py) contains the following code:
`from pkg_resources import get_distribution, DistributionNotFound` which is referenced in the version() function in the following manner: 

```    
try:
    las_version = get_distribution(__package__).version
except DistributionNotFound as err:
    logger.debug(err)
    pass
```

**Describe alternatives you've considered**
I've been able to use the module in my Python environment by commenting out the `from .las_version import version` and `__version__ = version()` portions of code in the [__init__](https://github.com/kinverarity1/lasio/blob/main/lasio/__init__.py) file. 

**Additional context**
I'm not sure if  [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources) or [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) would be viable alternatives.

**Comment by dcslagel** [comment] 2022-12-01 19:14
@sfc-gh-twhite ,

Can you add the Python environment issue/error message?

Also are there specific environment setups (Python version?, pyenv?, etc) that the issue is seen in?  

This information will help us reproduce the issue and verify any solutions.

Thanks!

DC

**Comment by dcslagel** [comment] 2022-12-01 19:16
Reference Notes:

https://setuptools.pypa.io/en/latest/pkg_resources.html

"Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources."

**Comment by dcslagel** [comment] 2023-01-20 22:35
@sfc-gh-twhite , @kinverarity1 

I made an exploratory branch  to either resolve this issue or gather more information about it:
https://github.com/dcslagel/lasio/tree/add_importlib.metadata_version_option_537_dev

**Comment by sfc-gh-twhite** [comment] 2023-01-23 14:27
I will give this a try today! I'm sorry for the delay; the environment in which I am testing this is difficult to reproduce. I can confirm it is a Python 3.8 environment where I encountered the error. I'm hopeful that `importlib` is available; I suspect it is. 

I will let you know today!

**Comment by sfc-gh-twhite** [comment] 2023-01-23 17:44
I gave this a try, it's still erroring on on the `__init__` due to the following import at the start of `las_version.py`. 

```
from pkg_resources import get_distribution, DistributionNotFound
```

I commented this line out and made some dummy variables to test with get_distribution and DistributionNotFound. It was still erroring out due to the nature of the way the package must be installed in the runtime environment. 

```
Traceback (most recent call last):
  File "/home/lasio.zip/lasio/__init__.py", line 63, in <module>
    __version__ = version()
  File "/home/lasio.zip/lasio/las_version.py", line 52, in version
    las_version = importlib.metadata.version(__package__)
  File "/usr/lib/importlib/metadata.py", line 530, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: lasio
 in function LAS_PARSE with handler run
```

I've been looking at a few other libraries. It seems they are building the `__version__` info statically or using an overly complex method using info pulled from the setup with configparser. 

While it's not ideal, in the `__init__` would it be possible to just null out the version if the function invocation fails?

```
from .las_version import version

try:
    __version__ = version()
except PackageNotFoundError:
    __version__ = None
```

**Comment by dcslagel** [comment] 2023-01-23 20:34
@sfc-gh-twhite, 

Thanks, for giving the branch a try and adding the information that the failure is occurring in a Python 3.8 environment.

I'll look at your results in detail and have a response today or tomorrow.

**Comment by dcslagel** [comment] 2023-01-23 23:24
@sfc-gh-twhite,

I was able to reproduce the error and a have a draft fix that I'll finish and post tomorrow or the day after.

Could you confirm/clarify a few points?
- setuptools ( the package that contains `pkg_resources`)  is not installed in the environment?
  - setuptools used to be reliably in most Python environments, but that is an assumption Lasio shouldn't make any more.
- Lasio was installed by some other method than Pip. 
  - How is Lasio installed?  Conda, Git, zip file, copying the file into place or some other method?

Thanks,
DC

**Comment by dcslagel** [comment] 2023-01-25 19:07
@sfc-gh-twhite , quick update, I'll be an additional day or 2 to have the draft fix available and posted.

**Comment by dcslagel** [comment] 2023-01-26 00:17
@sfc-gh-twhite , 

I've created pull-request: #546 Add importlib.metadata as option to get version to try to solve this issue.  Could you give it a try and verify if it solves the problems you were seeing?  It it doesn't could you post the result information incase some additional changes are needed to get it working.

Thanks!

**Comment by dcslagel** [comment] 2023-02-16 17:36
@sfc-gh-twhite ,  a fix for this has been merged to Lasio's main branch.  Could you give it a try to verify that it resolves the issue you were experiencing?

Thank you,
DC

**Comment by dcslagel** [comment] 2023-03-02 19:39
@sfc-gh-twhite ,  

Were you able to verify whether the main branch of Lasio with the fix #546 works for in your environment ?

Thanks,
DC

**Comment by reesehopkins** [comment] 2023-03-30 17:34
I ran into this issue today. I tried to test #546, but wasn't able to clone (it's my fault and has something to do with how I configured poetry). But I've run into this issue on an internal project I manage locally and `importlib.metadata` has worked for me.

**Comment by kinverarity1** [comment] 2023-03-31 04:52
@reesehopkins thanks for testing; can you confirm what issue you encountered, and which version of lasio you were using?

The fix referred to above (#546) has been merged to ``main`` but has not yet been released on pip i.e. the most recent version (v0.30) does not contain the fix.

**Comment by reesehopkins** [comment] 2023-04-06 01:28
I installed from `main` and it worked. Previously, I was using 0.30 and it didn't work.

**Comment by kinverarity1** [comment] 2023-04-07 06:25
Thanks!

**Closed** 2023-04-07 06:46 UTC
Labels: bug, enhancement
