### ISSUE TITLE
Reshape issue.

### ISSUE THREAD

**Issue by ThomasMGeo** [kinverarity1/lasio#323] opened 2020-05-01 05:08 UTC
Hi Kent et al.

This .las file does not want to read in, it seemed to have some weird unicode at the end of it. Is there a way to not read that in? Attached is the offending file. Once I removed it, read in just fine.

Zipped to make github happy.
[4900722364_722364A.las.zip](https://github.com/kinverarity1/lasio/files/4562580/4900722364_722364A.las.zip)

-TM

**Comment by kinverarity1** [comment] 2020-05-01 08:05
duplicate of #321

**Closed by kinverarity1** 2020-05-01 08:05 UTC
