### ISSUE TITLE
Exception creating LAS file without "parameters"

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#70] opened 2015-08-11 04:26 UTC
```python
from lasio import LASFile
from numpy import arange
from numpy.random import rand


def createFile(size):
    l = LASFile()
    depth = arange(size)
    data = rand(size)
    l.add_curve("DEPT", depth, unit="mm")
    l.add_curve("RND", data, descr="Random values")
    fn = "file" + str(size) + ".las"
    with open(fn, "w") as f:
        l.write(f, version=2.0)
    return fn
```

Exception:
```
Traceback (most recent call last):
  File "/app/main.py", line 23, in <module>
    f = createFile(size)
  File "/app/main.py", line 18, in createFile
    l.write(f, version=2.0)
  File "/usr/local/lib/python3.4/site-packages/lasio/las.py", line 353, in write
    section_widths = get_section_widths("params", self.params, version)
  File "/usr/local/lib/python3.4/site-packages/lasio/las.py", line 790, in get_section_widths
    section_widths["left_width"] = max([len(i.mnemonic) for i in items])
ValueError: max() arg is an empty sequence
```

**Comment by kinverarity1** [comment] 2015-08-11 04:39
This is a duplicate of #67, and I have a fix soon in PR #69. Thanks for picking up on it!

**Closed** 2015-08-11 05:57 UTC
